[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.flash_size = 16MB
board_build.psram_type = opi
board_build.arduino.memory_type = qio_opi
board_build.partitions = partitions.csv
board_build.filesystem = spiffs
build_flags =
    -DBOARD_HAS_PSRAM
monitor_speed = 115200
upload_port = /dev/cu.usbmodem5A790625861
monitor_port = /dev/cu.usbmodem5A790625861
